### ISSUE TITLE
fontmake: error: unrecognized arguments: --family-name Noto Sans Devanagari UI

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#133]
My bad: I looked at the log and discovered that NotoSansDevanagariUI was never built properly. When using the most recent submission https://github.com/googlei18n/noto-source/blob/master/src/NotoSansDevanagari/NotoSansDevanagariUI-MM.plist  we always got the error below.

@waksmonskiMT @JelleBosmaMT : I'm not sure if any of you are involved with these, but I wanted to ask if you know how NotoSansDevanagariUI-MM.plist was built on your side?

==== building src/NotoSansDevanagari/NotoSansDevanagariUI-MM.plist ====
usage: fontmake [-h] [-g GLYPHS_PATH] [-u UFO_PATHS [UFO_PATHS ...]]
                [-m MM_DESIGNSPACE]
                [-o {ufo,otf,ttf,ttf-interpolatable} [{ufo,otf,ttf,ttf-interpolatable} ...]]
                [-i] [--mti-source MTI_SOURCE] [--use-afdko] [--timing]
fontmake: error: unrecognized arguments: --family-name Noto Sans Devanagari UI

**Comment by JelleBosmaMT** [comment]
The plist we delived was  based on a sample package list on Githup.

I duly reported that it could not possible work and why: We cannot assign
OTL sources to UI masters because there are no UI masters. OTL sources
belong to interpolation coordinates of font families as expressed by
instances, that make use of masters. I made a proposal how a package list
could be made to work.

The plist that is at the link, is not what I make: We delivered one with
the UI and document definitions in a single file and without the cmap keys
being added. The addition of cmap references is a step forward, but as
long as you are trying to make fonts from masters that do not exist it is
bound to fail. In Glyphs sources where there is one font family only, the
plist format may appear to work. In that situation the assumption that
master equals font source works. But in Glyphs files masters and fonts
(instances) are separated and masters can be used as source for several
font families. Therefore the software to generate fonts from Glyphs
sources has to respect the hierarchy of the file format.

**Comment by jamesgk** [comment]
Sorry for the confusion here, I didn't realize this was throwing error messages. Devanagari UI is in kind of a transient state. This is because we can only interpolate UFOs, but have no way to unload OTL sources into UFOs. So my plan is to wait until we can interpolate OTF/TTFs and then we can 1) generate a set of master outlines from the Devanagari Glyphs source, 2) compile UI OTL sources for one set of masters and non-UI sources for another (these two sets of masters share the same outlines), and then 3) interpolate these sets of masters independently to get our final UI and non-UI output.

**Comment by marekjez86** [comment]
I doesn't appear to be relevant any longer but need to look at it in more detail later.

**Comment by jamesgk** [comment]
This shouldn't be an issue anymore since we can do binary interpolation with FontTools.
