### ISSUE TITLE
error compiling NotoSerifMyanmar: "Base master not found; no master at default location?"

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#303]
source: https://github.com/googlei18n/noto-source/tree/master/src/NotoSerifMyanmar

I'm not sure what to do about it... I haven't done anything with the master? is it something related to my environment?

============= src/NotoSerifMyanmar/NotoSerifMyanmar-MM.plist ==============
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSerifMyanmar-Light.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifMyanmar-Regular.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifMyanmar-Bold.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifMyanmar-CondensedLight.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifMyanmar-Condensed.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSerifMyanmar-CondensedBold.ufo
INFO:fontmake.font_project:Building interpolation-compatible TTFs
INFO:fontmake.font_project:Converting curves compatibly
INFO:cu2qu.ufo:New spline lengths:
1: 388
2: 5725
3: 429
4: 74
5: 12

INFO:fontmake.font_project:Saving TTF for NotoSerifMyanmar-Condensed
INFO:fontmake.font_project:Saving TTF for NotoSerifMyanmar-Regular
INFO:fontmake.font_project:Saving TTF for NotoSerifMyanmar-CondensedBold
INFO:fontmake.font_project:Saving TTF for NotoSerifMyanmar-Light
INFO:fontmake.font_project:Saving TTF for NotoSerifMyanmar-CondensedLight
INFO:fontmake.font_project:Saving TTF for NotoSerifMyanmar-Bold
INFO:fontmake.font_project:Building variable font variable_ttf/NotoSerifMyanmar-VF.ttf
INFO:fontTools.varLib:Internal master locations:
[{'weight': 28.0, 'width': 100.0},
 {'weight': 128.0, 'width': 100.0},
 {'weight': 194.0, 'width': 100.0},
 {'weight': 28.0, 'width': 70.0},
 {'weight': 128.0, 'width': 70.0},
 {'weight': 194.0, 'width': 70.0}]
INFO:fontTools.varLib:Internal axis supports:
{'weight': [28.0, 94.0, 194.0], 'width': [70.0, 100.0, 100.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'weight': -1.0, 'width': 0.0},
 {'weight': 0.34, 'width': 0.0},
 {'weight': 1.0, 'width': 0.0},
 {'weight': -1.0, 'width': -1.0},
 {'weight': 0.34, 'width': -1.0},
 {'weight': 1.0, 'width': -1.0}]
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.2.4.dev0', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/__main__.py", line 182, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 379, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 435, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 495, in run_from_ufos
    self.build_variable_font(designspace_path)
  File "/usr/local/google/home/marekj/newrel/fontmake/Lib/fontmake/font_project.py", line 228, in build_variable_font
    font, _, _ = varLib.build(designspace_path, finder)
  File "/usr/local/google/home/marekj/newrel/fonttools/Lib/fontTools/varLib/__init__.py", line 545, in build
    assert base_idx is not None, "Base master not found; no master at default location?"
AssertionError: Base master not found; no master at default location?

**Comment by anthrotype** [comment]
it's a glyphsLib+fonttools issue: https://github.com/googlei18n/glyphsLib/issues/170
It was introduced since glyphsLib 1.70, which added axes support, and fonttools 3.10.0, which added avar.

**Comment by marekjez86** [comment]
@anthrotype : this stops several of my builds right now

**Comment by anthrotype** [comment]
@marekjez86 can you try rebuilding with the latest fontmake v.1.2.4
https://github.com/googlei18n/noto-source/pull/76

I just tried building NotoSansMyanmar-VF.ttf with
```
./build variable src/NotoSansMyanmar/NotoSansMyanmar-MM.plist
```

and it worked.

**Comment by anthrotype** [comment]
Oh, it's the Serif sorry.. let me try that one.

**Comment by anthrotype** [comment]
ok, it's still failing..
I think I've found where the issue is in glyphsLib.. I'll fix it tomorrow.

**Comment by marekjez86** [comment]
@anthrotype : Thank you.

**Comment by anthrotype** [comment]
@marekjez86 if you add the new "Variation Font Origin" custom parameter to the NotoSerifMyanmar-MM.glyphs font (introduced since Glyphs 2.4.1), and set its value to "Light", then you should be able to build the variable font with the latest fontmake 1.2.5 (with [glyphsLib 1.7.3](https://github.com/googlei18n/glyphsLib/releases/tag/v1.7.3)).

<img width="295" alt="screenshot 2017-05-05 11 55 11" src="https://cloud.githubusercontent.com/assets/6939968/25742955/e24e35be-3189-11e7-84ce-02314182a17e.png">

I've also sent a PR to noto-souce repo to update the embedded fontmake submodule
https://github.com/googlei18n/noto-source/pull/77

The reason varLib fails without that custom parameter in the case of NotoSansMyanmar is that, without that, glyphsLib will fall back to using the master called "Regular" as the "base" master; this has weight value of 128 (in interpolation space); with that, glyphsLib attempts to find among the instances one whose interpolation weight is the same as the regular master weight value, in order to define the default location for the weight axis, _but_ does not find any in the case of NotoSansMyanmar (there is no instance defined with the same interpolation weight and width as the master called "Regular", the closest is the "SemiBold" instance which has interpolation weight 130); hence, glyphsLib defaults to 400 as the default (user-space) value for the weight axis; and this is mapped to interpolation weight 94, because the instance called "Regular" has weightClass 400 and interpolation weight 94.
Now, varLib takes this designspace and tries to build a variable font; if it finds an axes element in the designspace (this is always the case since glyphsLib 1.7.0), then it uses it to get the default value of each axis (in our case it's 400, mapped to 94); but then it fails because it cannot find any master which has default values along all the axes (i.e. the "base" master), since actually none of the NotoSansMyanmar masters happen to have weight 94.

This is a limitation of varLib, which expects that such a base master exists already in the sources (i.e. one whose location along all the axes corresponds to the default locations as defined in the axes element), as it can't currently create one on the fly.

One way to work around this limitation in the case of NotoSerifMyanmar is to add the "Variation Font Origin" custom parameter and set it to "Light" instead of "Regular". If you do that, then glyphsLib will use 100 as the default weight, not 400; and 100 is the weightClass of the "Thin" instance, which has the same interpolation weight (28) as the "Variation Font Origin" master, called "Light".

I know this is very confusing :,(

/cc @behdad @brawer

**Comment by anthrotype** [comment]
Related issue https://github.com/googlei18n/glyphsLib/issues/139

**Comment by marekjez86** [comment]
@anthrotype : thank you very much; i'll rebuild my tools and the fonts (after the mod). thanks again

**Comment by marekjez86** [comment]
verified as fixed.
how would I know as a end-user of fontmake to do it? is there anything I could place in fontmake FAQ?
