### ISSUE TITLE
noto_lint.py reports: no GPOS and GSUB tables in a font

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#330]
I built NotoSansAnatolianHieroglyphs-Regular.*tf fonts (see https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/otf/sans/NotoSansAnatolianHieroglyphs-Regular.otf and https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/ttf/sans/NotoSansAnatolianHieroglyphs-Regular.ttf ) from https://github.com/googlei18n/noto-source/blob/master/src/NotoSansAnatolianHieroglyphs-MM.glyphs

Then I tested them by running noto_lint.py on them (from https://github.com/googlei18n/nototools )
I get an error - please see below.

There are 4 possibilities:
1. a source error
2. noto_lint.py error
3. fontmake error compiling sources
4. ... something else

Could you help me to understand? In particular, if this is a source error then I'd like to be able to talk to MT.

```html
$ noto_lint.py *Anat*.otf
---
Automatic testing for 'sans,NotoSansAnatolianHieroglyphs-Regular.otf', Version 1.900:
E <complex/gpos/missing> There is no GPOS table in the font.
E <complex/gsub/missing> There is no GSUB table in the font.
Found 2 errors.
------
Finished linting 1 file.

$ noto_lint.py *Anat*.ttf
---
Automatic testing for 'sans,NotoSansAnatolianHieroglyphs-Regular.ttf', Version 1.900:
E <complex/gpos/missing> There is no GPOS table in the font.
E <complex/gsub/missing> There is no GSUB table in the font.
Found 2 errors.
------
Finished linting 1 file.
```

**Comment by punchcutter** [comment]
This is a source issue because there is no GPOS or GSUB in the source. According to the Unicode proposal there should be at least one mark (145B1) which should attach (GPOS) and possibly change shape in context (GSUB), but currently it does neither.

**Comment by punchcutter** [comment]
Looking at the Unicode proposal it appeared that one character should be a combining mark (145B1), but that was not accepted in the final implementation so there are no combining marks in Anatolian Hieroglyphs which means no GPOS is needed there. There are also 8 characters in the Unicode charts that show an informative note that they can be created by combining another character with 145B1 (proposed as a combining mark originally):
 
144A0 = 1449F + 145B1
144F0 = 144EF + 145B1
14546 = 14548 + 145B1
14555 = 1456E + 145B1
14562 = 14561 + 145B1
145A4 = 145A3 + 145B1
145B9 = 145B8 + 145B1
145F8 = 145F7 + 145B1

Since all of these are accessible through codepoints it's not necessary to add GSUB. 
That leaves the only issue being that noto_lint reports missing GPOS or GSUB as an error. I believe this should be a warning when both are missing, but if one exists and the other doesn't then it should be an error because of the requirement that an empty GSUB or GPOS should be added if the other exists and is not empty.

**Comment by marekjez86** [comment]
@punchcutter : thank you for the research.
@dougfelt : please see the last paragraph. Do we need a new issue in nototools (and I'll close this one) or could we use this issue and handle the noto_lint?

**Comment by dougfelt** [comment]
I'll just use this one.

**Comment by dougfelt** [comment]
Pushed a lint fix for this in nototools.
