### ISSUE TITLE
ttf build from UFO does not include name table platformID = 1 records

### ISSUE THREAD

**Issue by chrissimpkins** [googlei18n/fontmake#350]
fontmake v1.3.0 from PyPI
OS X 10.12.5
Python v3.6.2
UFO v2 source files

When I build ttf from UFO with fontmake using the following:

```
$ fontmake -u Hack-Regular.ufo
```

the name table includes only platformID = 3 / encodingID = 1 / languageID = 1033 records. 

![platformid_fontmake](https://user-images.githubusercontent.com/4249591/30033105-3e957da4-9167-11e7-86af-ab857e0189c2.png)

Validation tests in Font Book seem to indicate that the current version of OS X is happy without platformID = 1 name records:

![osx_test](https://user-images.githubusercontent.com/4249591/30033126-5a1f1e5e-9167-11e7-9e39-494f0422aa51.png)

however [Apple documentation](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html) seems to indicate otherwise:

> The supported platform identifier (platformID) codes are given in the following table. PlatformID codes have been assigned for Unicode, Macintosh, and Microsoft. PlatformID codes 240 through 255 have been reserved for user-defined platforms and are not available for registration. Names with platformIDs other than 0, 1, and 2 are ignored on OS X and iOS.

Are the platformID = 1 tables necessary for OS X users (including past releases of OS X) and, if so, is it possible to include these by default with fontmake builds?

**Comment by anthrotype** [comment]
> Are the platformID = 1 tables necessary for OS X users

No. AFAIK, they are only needed for pre-OSX Macintosh operating systems.
I don't know exactly from which version OSX they started to support platformID=3 (Microsoft) unicode nameIDs.

This could be a typo in Apple's TrueType spec; perhaps they meant "0, 1 and _3_" instead of "0, 1, and _2_ are ignored on OS X and iOS".

PlatformID=2 is deprecated/reserved, whereas platformID=3 (Microsoft, at least for the Unicode platform encodings 1 and 10, and the US English language 0x0409) definitely works on all the versions of OSX and iOS that I've come across.

> is it possible to include these by default with fontmake builds

At the moment the only way is to hard-code them in the fontinfo.plist using the UFO3's `openTypeNameRecords` proprerty (http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/).
I'd suggest you test and see whether you actually need these. Most likely you don't.

**Comment by chrissimpkins** [comment]
Thanks for the response Cosimo.  This supports  the validation report on OS X.  I suspect that you are correct.  This is likely a typo in the Apple docs.  

I went through numerous other fonts and they all seem to include the platformID 1 name tables.  Is there any benefit (web use, other font renderers) short of very old Mac systems where this may play a role?   If not, will close this.

**Comment by anthrotype** [comment]
browsers don't read the `name` table for embedded webfonts (name and style are declared via CSS).

**Comment by chrissimpkins** [comment]
Great, thanks for your help!  Will let you know if we come across any problems on any other platforms without the records.  Will close this IR.

**Comment by davelab6** [comment]
I heard that Mac Word 2010 needed them, and perhaps some other Carbon API
apps, but they are fading away

**Comment by chrissimpkins** [comment]
@davelab6 ty! Not aware of any use on Linux?
