### ISSUE TITLE
"Mac Postscript string is missing, but MS Postscript string is present" Font-Validator error

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontmake#414]
Using https://github.com/HinTak/Font-Validator/ on OTF produced by the pipeline from https://github.com/googlei18n/noto-source/blob/master/src/NotoSansHatran-MM.glyphs produces three errors:

![os2](https://user-images.githubusercontent.com/13322623/38447293-4f44d4ae-39b1-11e8-8dcc-a81f295d53d8.jpeg)
![name](https://user-images.githubusercontent.com/13322623/38447297-54641d46-39b1-11e8-93ce-5816f7a68696.jpeg)

While the first error happens also when dealing with the Glyphs.app , the second one is unique to the fontmake. Is this a fontmake issue or a feature that we shouldn't worry about?

**Comment by khaledhosny** [comment]
The first error is dubious, bit 8 **is** defined in [`fsSelection`](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fsselection). The second error is probably useless too since no application should require the old Mac name fields.

**Comment by marekjez86** [comment]
@khaledhosny : this teaches me that I shouldn't rely too much on this tool

**Comment by anthrotype** [comment]
as Khaled said, bit 8 of OS/2.fsSelection is not "undefined", it was defined in the OT spec since version 4 of OS/2 table (fontmake outputs a version 4 OS/2 table).
So that's a bug in FontValidator and should be reported there.

As for the second issue, fontmake deliberately only includes 2-byte name strings ("windows" platform, but actually work everywhere)
See https://github.com/googlei18n/ufo2ft/issues/243

The fact that Glyphs.app-generated fonts have the fsSelection bit 8 set, whereas fontmake doesn't, it looks like it is a missing feature that we should probably add support for (in ufo2ft).

> If bit 8 is set in OS/2 table v. 4, then ‘name’ strings for family and subfamily are provided that are consistent with a weight/width/slope family model without requiring the use of ‘name’ IDs 21 or 22.

https://docs.microsoft.com/en-us/typography/opentype/spec/os2ver4#fss

I'll open an issue in ufo2ft

**Comment by davelab6** [comment]
> this teaches me that I shouldn't rely too much on this tool

Sadly, the checks in this tool are very old, and I heard a rumor that not even MS font developers use it any more. 

However, there are checks in that are not implemented anywhere else.

So, you have to know a lot about the context of font technology in order to better interpret the check results. It would be nice to update them, so that is not needed, of course.

**Comment by marekjez86** [comment]
I'm closing this issue since this is not a fontmake problem and an issue https://github.com/HinTak/Font-Validator/issues/34 is open in HinTak/Font-Validator (that's what I used)
